# Generated by Django 3.0.3 on 2020-10-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JOBID', models.CharField(max_length=20, unique=True)),
                ('client', models.CharField(max_length=255)),
                ('field', models.CharField(blank=True, max_length=255)),
                ('well', models.CharField(max_length=255)),
                ('country', models.CharField(default='Iraq', max_length=255)),
                ('BU', models.CharField(default='KIU', max_length=3)),
                ('BL', models.CharField(default='SWT', max_length=3)),
                ('description', models.CharField(blank=True, max_length=800)),
                ('isContract', models.BooleanField(default=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
    ]
