# Generated by Django 3.0.3 on 2020-10-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FAR', '0004_auto_20201010_1917'),
        ('Jobs', '0003_auto_20201012_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMasterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h2s', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('co2', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('oilRate', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('gasRate', models.DecimalField(blank=True, decimal_places=3, max_digits=3)),
                ('description', models.CharField(blank=True, max_length=800)),
                ('assets', models.ManyToManyField(null=True, to='FAR.FAR_DB')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.JobsDB')),
            ],
        ),
    ]
