# Generated by Django 3.0.3 on 2020-10-17 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0005_auto_20201016_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobmasterinfo',
            options={'ordering': ['job']},
        ),
        migrations.AlterModelOptions(
            name='jobsdb',
            options={'ordering': ['client']},
        ),
    ]
