# Generated by Django 3.0.3 on 2020-10-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0006_auto_20201017_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsdb',
            name='BL',
            field=models.CharField(blank=True, default='SWT', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='jobsdb',
            name='BU',
            field=models.CharField(blank=True, default='KIU', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='jobsdb',
            name='description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='jobsdb',
            name='field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobsdb',
            name='isContract',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobsdb',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobsdb',
            name='well',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
