# Generated by Django 3.1.2 on 2020-10-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0008_jobsdb_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsdb',
            name='files',
            field=models.FileField(null=True, upload_to='jobsFiles/', verbose_name=''),
        ),
    ]
