# Generated by Django 3.1.2 on 2020-11-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0009_auto_20201031_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsdb',
            name='files',
        ),
    ]
