# Generated by Django 3.1.2 on 2021-02-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0011_auto_20201101_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsdb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
