# Generated by Django 3.0.3 on 2020-10-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedb',
            name='BL',
            field=models.CharField(default='SWT', max_length=3),
        ),
        migrations.AddField(
            model_name='employeedb',
            name='BU',
            field=models.CharField(default='KIU', max_length=3),
        ),
        migrations.AddField(
            model_name='employeedb',
            name='isEmployee',
            field=models.BooleanField(default=True),
        ),
    ]
