# Generated by Django 3.1.2 on 2020-10-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_auto_20201017_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedb',
            name='seniority_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
