# Generated by Django 3.0.3 on 2020-10-13 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FAR', '0004_auto_20201010_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_date_start', models.DateField()),
                ('ms_type', models.CharField(max_length=20)),
                ('main_date_end', models.DateField()),
                ('main_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expiry_date', models.DateField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FAR.FAR_DB')),
            ],
        ),
    ]
