# Generated by Django 3.0.3 on 2020-10-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancedb',
            name='expiry_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='maintenancedb',
            name='main_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='maintenancedb',
            name='main_date_end',
            field=models.DateField(blank=True),
        ),
    ]
