# Generated by Django 3.0.3 on 2020-10-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maintenance', '0002_auto_20201013_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancedb',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancedb',
            name='main_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancedb',
            name='main_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancedb',
            name='main_date_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenancedb',
            name='ms_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
