# Generated by Django 3.1.2 on 2020-10-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maintenance', '0003_auto_20201019_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancedb',
            name='description',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
