# Generated by Django 3.1.2 on 2020-10-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maintenance', '0004_maintenancedb_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancedb',
            name='main_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
