# Generated by Django 3.0.3 on 2020-10-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAR_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_num', models.CharField(max_length=200, unique=True)),
                ('serial_num', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=800)),
                ('BU', models.CharField(max_length=4)),
                ('BL', models.CharField(max_length=4)),
                ('asset_lift', models.IntegerField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tot_dep_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nbv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acquisition_date', models.DateField()),
                ('equ_type', models.CharField(max_length=200)),
                ('temp_location', models.CharField(max_length=200)),
            ],
        ),
    ]
