# Generated by Django 3.0.3 on 2020-10-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='far_db',
            name='serial_num',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
