# Generated by Django 3.0.3 on 2020-10-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAR', '0002_auto_20201006_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='far_db',
            old_name='asset_lift',
            new_name='asset_life',
        ),
    ]
