# Generated by Django 3.0.3 on 2020-10-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAR', '0003_auto_20201006_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='far_db',
            name='temp_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
