# Generated by Django 3.0.3 on 2020-10-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAR', '0005_auto_20201017_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='far_db',
            name='BL',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='far_db',
            name='BU',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='far_db',
            name='acquisition_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='far_db',
            name='acquisition_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='far_db',
            name='asset_life',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='far_db',
            name='description',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='far_db',
            name='equ_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='far_db',
            name='nbv',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='far_db',
            name='temp_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='far_db',
            name='tot_dep_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
